version: '3.8'
services:
  postgres:
    container_name: unicom-postgres
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - postgres:/var/lib/postgresql/data

  unicom-backend:
    container_name: unicom-backend
    image: unicom-backend
    build: '.'
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres

  elasticsearch:
    container_name: unicom-elasticsearch
    image: elasticsearch:7.17.6
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"

volumes:
  postgres:
    driver: local
  es_data:
    driver: local