version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  unicom-backend:
    image: unicom-backend
    build: '.'
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
volumes:
  postgres:
    driver: local