version: '3.8'

services:
  postgres:
    container_name: unicom-postgres
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  unicom-backend:
    container_name: unicom-backend
    image: unicom-backend
    build: '.'
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres

  elasticsearch:
    container_name: unicom-elasticsearch
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200

  kibana:
    container_name: unicom-kibana
    image: kibana:8.2.2
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch

volumes:
  postgres:
    driver: local
  es_data:
    driver: local