project:
  version: @project.version@

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://${postgres.host:localhost}:${postgres.port:5432}/${postgres.db:postgres}?autoReconnect=true&enabledTLSProtocols=TLSv1.2
    username: ${postgres.user:postgres}
    password: ${postgres.password:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  liquibase:
    change-log: 'classpath:db/changelog/changelog-root.yml'

server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto`