@startuml

node "Unicom Backend" as unicomBackend {
    together {
        interface " " as suggestInt
        component "Suggest" as suggest
        suggest - suggestInt

        interface REST
        component "FHIR Server" as fhir
        fhir - REST
    }

    together {
        component "Substitution" as substitution
        interface "REST" as substitutionInt
        substitution - substitutionInt
    }

    database "IDMP Database" as idmpDb

    idmpDb <.r. fhir
    idmpDb <.r. suggest
    suggest -[hidden]- fhir
    REST <.. substitution
}

together {
    interface "QR Code" as qrCodeUser
    interface "QR Code" as qrCodePharmacist
}

together {
    node "User Facing App" as userApp {
    }

    userApp .d.> qrCodePharmacist
    userApp -d- qrCodeUser
    suggestInt <.l. userApp

    note top of userApp {
        HealthPass
        InfoSage
        Pharmawizard Experimental App
    }
}

cloud "eHDSI" {
    together {
        component "Medication list" as medicationList

        interface " " as medicationListInt
        medicationListInt - medicationList
    }
}

userApp .r.> medicationListInt
userApp .> REST

together {
    node "Healthcare Provider App" as pharmacistApp

    qrCodeUser <.d. pharmacistApp
    qrCodePharmacist -d- pharmacistApp
    substitutionInt <.l. pharmacistApp
}

unicomBackend -[hidden] userApp

pharmacistApp .> REST

@enduml