@startuml
'https://plantuml.com/class-diagram

package "IDMP Datamodel" as idmpDatamodel <<frame>> {
    entity Strength {
        concentrationNumeratorValue: Float
        concentrationNnumeratorUnit: UcumUnit
        concentrationDenominatorValue: Float
        concentrationDdenominatorUnit: UcumUnit
        presentationNumeratorValue: Float
        presentationNnumeratorUnit: UcumUnit
        presentationDenominatorValue: Float
        presentationDdenominatorUnit: UcumUnit
    }

    entity Ingredient {
        ReferenceSubstance: EmaSporSms
        Substance: EmaSporSms
        Role: SporRms
    }

    together {
        entity RoutesOfAdministration {
            routeOfAdministration: EdqmRouteOfAdministration
        }

        entity PharmaceuticalProduct {
            phpId: IdmpPhpId
            administrableDoseForm: EdqmDoseForm
            unitOfPresentation: EdqmUnitOfPresentation
        }
    }

    entity MedicinalProduct {
        * pmsId: Integer <<generated>>
        --
        mpId: IdmpMpId
        fullName: String
        authorizedPharmaceuticalDoseForm: EdqmDoseForm
        marketingAuthorizationHolder: SporOms
    }

    entity AtcCode {
        atcCode: String
    }

    entity PackagedMedicinalProduct {
        pcId: IdmpPcId
        packSize: Integer
    }

    entity PackageItem {
        type: EdqmPackageItemType
        packageItemQuantity: Integer
    }

    entity ManufactoredItem {
        manufactoredDoseForm: EdqmDoseForm
        unitOfPresentation: EdqmUnitOfPresentation
        manufactoredItemQuantity: Integer
    }

    MedicinalProduct ||--|{ AtcCode

    Strength ||--o| Ingredient : "referenceStrength"
    Strength |o--o| Ingredient : "strength"

    Ingredient }|-o{ ManufactoredItem : "ingredients <<redundant>>"
    Ingredient }|--o{ PharmaceuticalProduct : "ingredients"

    RoutesOfAdministration }|-r-|| PharmaceuticalProduct : "routesOfAdministration"
    PharmaceuticalProduct ||--o{ MedicinalProduct : "pharmaceuticalProduct"
    MedicinalProduct ||-o{ PackagedMedicinalProduct : "medicinalProduct"
    PackagedMedicinalProduct |o-|{ PackageItem : "packagedMedicinalProduct"
    PackageItem |o-o{ PackageItem : "packageItem"
    ManufactoredItem ||--o{ PackageItem : "packageItem"
}

@enduml