@startuml
'skinparam linetype ortho

package "Data Model" as datamodel <<frame>> {
    enum IDMPDoseForm {}
    enum Country {}

    entity IdmpSubstance {
        name: String
    }

    entity IdmpMedicinalProduct {
        name: String
        doseForm: IDMPDoseForm
        packageSize: Integer
    }

    entity Organization {
        name: String
    }

    package "Local Data" as local <<frame>> {
        class LocalMedicinalProductData {
            country: Country
            data: Json
        }

        class LocalSubstanceData {
            country: Country
            data: Json
        }

        LocalMedicinalProductData --> Country
        LocalMedicinalProductData "*" --* "1" IdmpMedicinalProduct

        LocalSubstanceData --> Country
        LocalSubstanceData "*" --* "1" IdmpSubstance
    }

    IdmpMedicinalProduct --> IDMPDoseForm
    IdmpMedicinalProduct "*" --o "1" Organization : manufacturer
    IdmpMedicinalProduct "*" --o "1..*" IdmpSubstance : ingredients
}

@enduml