@startuml
'https://plantuml.com/class-diagram

package "IDMP Datamodel" as idmpDatamodel <<frame>> {
    entity Strength {
        * id: Integer <<generated>>
        --
        concentrationNumeratorValue: Float
        concentrationNnumeratorUnit: UcumUnit
        concentrationDenominatorValue: Float
        concentrationDdenominatorUnit: UcumUnit
        presentationNumeratorValue: Float
        presentationNnumeratorUnit: UcumUnit
        presentationDenominatorValue: Float
        presentationDdenominatorUnit: UcumUnit
    }

    entity Ingredient {
        * id: Integer <<generated>>
        --
        referenceSubstance: EmaSporSms
        substance: EmaSporSms
        role: SporRms
    }

    together {
        entity RouteOfAdministration {
            * id: Integer <<generated>>
            --
            routeOfAdministration: EdqmRouteOfAdministration
        }

        entity PharmaceuticalProduct {
            * id: Integer <<generated>>
            --
            phpId: IdmpPhpId
            administrableDoseForm: EdqmDoseForm
            unitOfPresentation: EdqmUnitOfPresentation
        }
    }

    entity MedicinalProduct {
        * id: Integer <<generated>>
        --
        mpId: IdmpMpId
        country: IsoCountryCode
        fullName: String
        authorizedPharmaceuticalDoseForm: EdqmDoseForm
        marketingAuthorizationHolder: SporOms
    }

    entity AtcCode {
        * id: Integer <<generated>>
        --
        atcCode: String
    }

    entity PackagedMedicinalProduct {
        * id: Integer <<generated>>
        --
        pcId: IdmpPcId
        packSize: Integer
    }

    entity PackageItem {
        * id: Integer <<generated>>
        --
        type: EdqmPackageItemType
        packageItemQuantity: Integer
    }

    entity ManufacturedItem {
        * id: Integer <<generated>>
        --
        manufacturedDoseForm: EdqmDoseForm
        unitOfPresentation: EdqmUnitOfPresentation
        manufacturedItemQuantity: Integer
    }

    MedicinalProduct ||--|{ AtcCode : "atcCodes"

    Strength ||--o| Ingredient : "referenceStrength"
    Strength |o--o| Ingredient : "strength"

    Ingredient }|-o{ ManufacturedItem : "ingredients <<redundant>>"
    Ingredient }|--o{ PharmaceuticalProduct : "ingredients"

    RouteOfAdministration }|-r-|| PharmaceuticalProduct : "routesOfAdministration"
    PharmaceuticalProduct ||--o{ MedicinalProduct : "pharmaceuticalProduct"
    MedicinalProduct ||-o{ PackagedMedicinalProduct : "medicinalProduct"
    PackagedMedicinalProduct |o-|{ PackageItem : "packagedMedicinalProduct"
    PackageItem |o-o{ PackageItem : "packageItem"
    ManufacturedItem ||--o{ PackageItem : "packageItem"
}

@enduml