@startuml
'https://plantuml.com/class-diagram

package "IDMP Datamodel" as idmpDatamodel <<frame>> {
    entity EdqmRouteOfAdministration {
        * id: Long
        --
        * display: String
    }

    entity EdqmUnitOfPresentation {
        * id: Long
        --
        * display: String
    }

    together {
        entity EdqmDoseForm {
            * id: Long
            --
            * display: String
            * isValidAdministrableDoseForm: Boolean
        }

        entity Strength {
            * id: Long
            --
            * numeratorValue: Float
            * numeratorUnit: Unit
            denominatorValue: Float
            denominatorUnit: Unit
            * isPresentationStrength: Boolean
        }

        entity SubstanceWithRolePai {
            * id: Long
            --
            * ingredientCode: String {unique}
            * moiety: String
            modifier: String
        }
    }

    entity PharmaceuticalProduct {
        * id: Long
        --
        * phpId: String {unique}
    }

    entity MedicinalProduct {
        * id: Long
        --
        * mpId: String {unique}
        * country: Country
        * fullName: String
        * packSize: Integer
        * atcCode: String
        packDescription: String
    }

    entity PackagedMedicinalProduct {
        * id: Long
        --
        * pcId: String {unique}
        * packageSize: Integer
    }

    entity Organization {
        * id: Long
        --
        * name: String
    }

    SubstanceWithRolePai ||------o{ PharmaceuticalProduct : preciseActiveIngredient
    EdqmDoseForm ||--o{ PharmaceuticalProduct : administrableDoseForm
    Strength ||--|| PharmaceuticalProduct : normalizedStrength

    PharmaceuticalProduct ||--o{ MedicinalProduct : pharmaceuticalProduct

    MedicinalProduct ||--o{ PackagedMedicinalProduct : medicinalProduct
    MedicinalProduct }o--|| EdqmDoseForm : pharmaceuticalDoseForm
    MedicinalProduct ||--|| Strength : authorizedStrength
    EdqmRouteOfAdministration }o-o{ MedicinalProduct : routesOfAdministration
    EdqmUnitOfPresentation ||--o{ Strength: unitOfPresentation

    MedicinalProduct }o-|| Organization : marketingAuthorizationHolder

    Strength }o-|| SubstanceWithRolePai : referenceSubstance
}
@enduml