@startuml
'https://plantuml.com/class-diagram

package "IDMP Datamodel" as idmpDatamodel <<frame>> {
    entity RouteOfAdministration {
        display: String
    }

    entity UnitOfPresentation {
        display: String
    }

    together {
        entity DoseForm {
            display: String
        }

        entity Strength {
            numeratorValue: Float
            denominatorValue: Float
            numeratorUnit: Unit
            denominatorUnit: Unit
            referenceSubstance: ReferenceSubstance
        }

        entity Substance {
            name: String
        }
    }

    entity PharmaceuticalProduct {
        phpId: String
        ingredientCode: String
    }

    entity MedicinalProduct {
        mpId: String
        fullName: String
        packSize: Integer
        packDescription: String
    }

    entity PackagedProduct {
        pcId: String
        atcCode: String
        packageSize: Integer
    }

    entity Organization {
        name: String
    }

    Substance "1" o---- "*" PharmaceuticalProduct : activeIngredient
    Substance "0..1" o---- "*" PharmaceuticalProduct : modifier
    DoseForm "1" o-- "*" PharmaceuticalProduct : doseForm
    Strength "1" -- "1" PharmaceuticalProduct : strength

    PharmaceuticalProduct "1" o-- "*" MedicinalProduct : pharmaceuticalProduct

    MedicinalProduct "1" o-- "*" PackagedProduct : medicinalProduct
    MedicinalProduct "*" --o "1" DoseForm : administrableDoseForm
    RouteOfAdministration "*" - "*" MedicinalProduct : routesOfAdministration
    UnitOfPresentation "1" -* "*" MedicinalProduct : unitOfPresentation

    MedicinalProduct "*" -o "1" Organization : marketingAuthorizationHolder

    RouteOfAdministration -[hidden]-> UnitOfPresentation
}
@enduml