@startuml

package "Data Model" as datamodel <<frame>> {
    entity MedicinalProductDefinition {
        mpId
        fullName

        pcId
        description: String

        packageSize: Float
        unitOfPresentation
        phpId
        doseForm
        atcCode: String
        routeOfAdministration

    }

    entity Organization {
        name: String
    }

    entity Ingredient {
        code: EU-SMS
        strengthPresentation
        strengthConcentration
        referenceSubstance: NONHOIDEA
        referenceStrength: NONHOIDEA
    }

    entity SubstanceDefinition {
        name: String
    }

    MedicinalProductDefinition "*" -o "1" Organization : "Marketing Authorization Holder"

    MedicinalProductDefinition "*" -- "*" SubstanceDefinition
    (MedicinalProductDefinition, SubstanceDefinition) .. Ingredient
}


note right of datamodel {
    **Assumptions made:**
    * One and only one manufactored item per per packaged product
        => incorporate Contains and ManufactoredItemDefinition into PackagedProductDefinition
    
    * in the end
        => incorporate PackagedProductDefinition inside MedicinalProductDefinition
}


@enduml