@startuml
skinparam actorStyle awesome

actor User as user

participant "User Facing App" as user_app

participant "Healthcare Provider App" as provider_app
 
actor "Healthcare Provider" as provider

box "Unicom Backend"
    participant "Suggest" as suggest
    participant "Substitution" as substitution
    participant "T6.1 FHIR Server" as fhir
    database "T6.1 IDMP Database" as db
end box

group Smart Substitution
    activate user
    user -> user_app : Selects drug
        activate user_app
            user_app -> user_app : Generate QR of selected drug
            user_app -> provider_app : User shows QR

            activate provider_app
                provider_app -> substitution : Call substitution component
                                
                activate substitution
                    substitution -> fhir : Make some calls (TBD)

                    activate fhir
                        fhir -> db : Do queries
                        activate db
                            db --> fhir : Return IDMP data
                        deactivate db

                        fhir -> fhir : Encapsulate IDMP data in FHIR resources

                        fhir --> substitution : Return resources
                    deactivate fhir

                    substitution --> provider_app : Return list of candidate substitute drugs
                deactivate substitution

                provider_app -> provider : Ask to chose substitute drug
                activate provider
                    provider --> provider_app : Select best substitute drug
                deactivate provider

                provider_app -> provider_app : Generate QR of substitute drug
                provider_app --> user_app : Healthcare provider shows QR
            deactivate provider_app

            user_app -> user_app : Save substitute of selected drug
            user_app --> user : Show substitue drug to the user
        deactivate user_app
    deactivate user
end

@enduml